# Generated by Django 5.0.4 on 2024-04-05 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0002_remove_product_price_sale_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
